import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const tangerine = localFont({
  src: [
    { path: "../public/fonts/Tangerine-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Tangerine-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-tangerine",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${tangerine.variable} font-montserrat antialiased`}
      >
        {children}
      </body>
    </html>
  );
}